language: python
python:
  - "3.6"


# command to install dependencies
jobs:
  include:
    - stage: install
      script: pip install ./
    - stage: build
      script: python setup.py sdist
      script: python setup.py bdist_wheel  
    - stage: tests
      script: pip install ./; pip install pytest; pytest tests/
    - stage: upload
      script: pip install twine; rm -rf dist/ ; python setup.py sdist; python setup.py bdist_wheel; twine upload --skip-existing -u $TWINE_USERNAME -p $TWINE_PASSWORD dist/*

    