language: python
python:
  - "3.6"

# command to install dependencies
install_deps: 
  - pip install coverage
  - pip install coveralls
  
build:
  - python setup.py sdist
  - python setup.py bdist_wheel

script:
  - pip install ./

tests:
  - echo "MOCK"

upload:
  - echo "MOCK"
  